version: '3'

volumes:
  db_value_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - db_value_production:/var/lib/postgresql/data
  backend:
    image: excellent84/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/media
  frontend:
    image: excellent84/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: nginx:1.19.3
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/static
      - media_volume:/media
    ports:
      - 80:80